INSERT INTO wines (id,
                   vendor_code,
                   quality_level,
                   reserve_type,
                   name,
                   short_name,
                   year,
                   taste_wine,
                   average_rating_score,
                   price,
                   grape,
                   is_decantation,
                   wine_type,
                   strength_from,
                   strength_to,
                   wine_color,
                   color_describing,
                   taste,
                   aroma,
                   gastronomy,
                   description)
VALUES (20,
        'MRD2019',
        'Select',
        NULL,
        'Prince Trubetskoi Select Riesling',
        'Riesling',
        2019,
        'asian food',
        0.00,
        870.00,
        'Riesling',
        FALSE,
        'DRY',
        10.6,
        12.9,
        'WHITE',
        'citric',
        'delicate, balanced, round, with a fruity and honey aftertaste.',
        'soft, generous, multifaceted, with hints of tropical fruits, notes of lychee and peach',
        'Recommended for oriental dishes and fruits.',
        'Vineyards stretch on the slopes of the Kakhovka reservoir. The unique terroir produces excellent wines. The harvest is harvested and sorted by hand. Fermentation of the wine, as well as maturation, takes place in tanks and is strictly controlled. Riesling is incredibly generous, multi-faceted and aromatic. Pleasant fruity and honey shades will give a truly vivid impression. Everyone likes this wine and is absolutely universal');

INSERT INTO wines (id,
                   vendor_code,
                   quality_level,
                   reserve_type,
                   name,
                   short_name,
                   year,
                   taste_wine,
                   average_rating_score,
                   price,
                   grape,
                   is_decantation,
                   wine_type,
                   strength_from,
                   strength_to,
                   wine_color,
                   color_describing,
                   taste,
                   aroma,
                   gastronomy,
                   description)
VALUES (21,
        'MRD2021',
        'Select',
        'Limeted Edition Vine',
        'Prince Trubetskoi Select Malbec',
        'Malbec',
        2019,
        'red meat',
        0.00,
        870.00,
        'Malbec',
        FALSE,
        'DRY',
        10.60,
        12.90,
        'RED',
        'deep rich with ruby tint',
        'bright harmonious, berry with a delicate aftertaste and round tannins',
        'berry with a hint of milk chocolate with notes of black cherry, pomegranate, plum, raspberry, blackberry and blueberry',
        'goes well with meat dishes - stewed and fried meat, roast beef, steaks.',
        'The wine is made in a limited edition. Harvesting took place entirely by hand on a site with an area of 5 hectares and which stretches on the slopes of the Dnieper with a south-eastern exposure. In order to achieve the highest quality grapes, the volume of the harvest was limited. The soil of the terroir is southern weakly humus-accumulative medium loamy chernozem. The wine has a magnificent bright character. The generous aromatic bouquet reveals notes of red berries, raspberries, blackberries, blueberries, plums. This wine will be an excellent accompaniment to meat dishes, as well as for solo consumption');
